#!/usr/bin/env tsx
// Reads web/services/*.yaml, validates against the Service schema, and emits a
// typed SERVICES literal at web/src/lib/services.generated.ts. Every value in
// the output comes from the config files, so the result is identical whether
// the build runs on a laptop, in CI, or inside the image (ADR 0015).

import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";
import { parse as parseYaml } from "yaml";
import { validateService } from "./lib/validate-service";
import type { Service } from "../src/lib/types";

const SERVICES_DIR = path.join(import.meta.dirname, "..", "services");
const OUT_PATH = path.join(import.meta.dirname, "..", "src", "lib", "services.generated.ts");

async function main() {
  const files = (await readdir(SERVICES_DIR)).filter((f) => f.endsWith(".yaml") || f.endsWith(".yml")).sort();
  console.error(`[services] found ${files.length} service config file(s)`);
  const services: Service[] = [];
  for (const f of files) {
    const abs = path.join(SERVICES_DIR, f);
    const text = await readFile(abs, "utf8");
    const raw = parseYaml(text);
    services.push(validateService(raw, f));
  }
  await mkdir(path.dirname(OUT_PATH), { recursive: true });
  const body = `// AUTO-GENERATED by scripts/build-services.ts — do not edit.
import type { Service } from "./types";

export const SERVICES: Service[] = ${JSON.stringify(services, null, 2)};
`;
  await writeFile(OUT_PATH, body);
  console.error(`[services] wrote ${OUT_PATH} (${services.length} services)`);
}

main().catch((e) => { console.error(e); process.exit(1); });
